### ISSUE TITLE
Device compatibility check

### ISSUE THREAD

**Issue by lampensau** [bitfocus/companion-module-greengo-intercom#1]
I've tested and verified the functionality of this module in combination with these device types running the [osc-remote.gg5t](https://github.com/bitfocus/companion-module-greengo-intercom/blob/master/osc-remote.gg5t) script:

**User Stations:**
- [x] BCN beacon light 
- [x] BPX belt pack
- [x] MCX rack station
- [x] MCXD desk station
- [x] ~WAA antenna~ (currently can't be supported)
- [x] ~WBPX belt pack~ (currently can't be supported)
- [x] WPX wall panel

**Interfaces:**
- [x] ~BridgeX interface~ (currently can't be supported)
- [x] DNTI interface
- [x] ~INTX interface~ (currently can't be supported reliably)
- [x] Q4WR interface
- [x] RDX interface (does not support actions for input.source ~or audio.gain~)
- [x] Si2WR interface (does not support actions for input.source)
- [x] Si4WR interface

I will verify as many devices as possible in the coming days. However, I currently don't have access to these device types: BridgeX, DNTI, Q4WR, ~RDX~, and Si2WR.

**Comment by lampensau** [comment]
Closing this as we've tested all possible devices.

**Comment by josephdadams** [comment]
@lampensau ready for me to put this in the beta builds?

**Comment by lampensau** [comment]
Yes, I think the current module is ready for a broader audience ...
