### ISSUE TITLE
Feedback is not working

### ISSUE THREAD

**Issue by gijsvisser1981** [bitfocus/companion-module-greengo-intercom#5]
Hello,

I got the module to work. Thank you. (lost some time to find a working controllport: 12321)
Only the feedback is not working. Is there something I am doing wrong?
All the variables are there, but they don't change.

Thank you already for the great work!

**Comment by lampensau** [comment]
Hey @gijsvisser1981,

It's interesting that it took some time for you to find a working port (I usually use `8000` without any issues). You should definitely choose a port number that is not in use by any other application on your network or PC.

Usually, a non-working feedback from your Green-GO device means one of the following:

- The `remoteIP` or `remotePort` variables in the `osc-remote.gg5t` script do not match the IP address/port that Companion is using ([reference](https://github.com/bitfocus/companion-module-greengo-intercom/blob/master/osc-remote.gg5t#L4-L5))
- Something is blocking communication on the defined port for the Companion module (e.g., Windows firewall)
- You have multiple devices reporting to the same `remoteIP` and `remotePort`. However, this should actually still produce feedbacks, even though there is no guarantee that the given feedback is correct (one device has activated talk on channel 1, the other does not)

**Comment by gijsvisser1981** [comment]
Great,

I doublechecked everything, used an unused port, 
Everything is working.

Thank you very much.
Great work!

**Comment by lampensau** [comment]
Thanks for the feedback :)
